id: AC850EC59
title: Section 20
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:43:21.577170
  last_modified_at: 2022-03-01 21:43:21.577173
