id: AC850EC59
title: Section 4
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:43:21.587817
  last_modified_at: 2022-03-01 21:43:21.587821
